### ISSUE TITLE
Improve error handling on 502 error

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/hugie#29]
I experienced a random 502 error today that was not handled very nicely:

```
(foo)    ~/Documents/mantis/hfie   main ±  hfie endpoint list                     
Traceback (most recent call last):                
  File "/home/matthew/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)                                                                        
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())                                                       
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                                                                         
During handling of the above exception, another exception occurred:
                                                                                                         
Traceback (most recent call last):
  File "/home/matthew/.local/bin/hfie", line 8, in <module>                                  
    sys.exit(app())                                                                                      
  File "/home/matthew/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)                                                            
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)             
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main 
    rv = self.invoke(ctx)             
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke  
    return ctx.invoke(self.callback, **ctx.params)                                                       
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)     
  File "/home/matthew/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/matthew/.local/lib/python3.8/site-packages/hfie/endpoint.py", line 29, in list
    data = response.json()
  File "/home/matthew/.local/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)             
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>                                                                                                  
</html>  
```

**Comment by nsorros** [comment]
This should be improved

**Comment by nsorros** [comment]
Not sure what is causing this but looking at the documentation they only document a `401` error. I wonder whether the 5xx errors happen when their API is down. I am closing this for now and will reopen with a suggestion to catch `401` and `5x` for listing endpoints
