### ISSUE TITLE
Intermittent issue reading jsons

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/hugie#40]
I occasionally get this:

```
hugie endpoint create inference_endpoint_configs/oms-nlu-development.json              <aws:oms-voice-dev>
Traceback (most recent call last):

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)

  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/matthew/.local/bin/hugie", line 8, in <module>
    sys.exit(app())

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.8/site-packages/hugie/endpoint.py", line 77, in create
    if response.json().get("error"):

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

for json:
```
{
  "accountId":null,
  "api_type":"protected",
  "compute":{
    "accelerator":"cpu",
    "instanceSize":"small",
    "instanceType":"c6i",
    "scaling":{
      "minReplica":1,
      "maxReplica":1
    }
  },
  "model":{
    "framework":"custom",
    "image":{
      "huggingface":{
      }
    },
    "repository":"<redacted>",
    "revision":"<redacted>",
    "task":"text-classification"
  },
  "name":"<redacted>",
  "provider":{
    "vendor":"aws",
    "region":"us-east-1"
  }
}
```
I can read it with `json.load` and `srsly.read_json`, but it `hugie` doesn't like reading it. Bit weird.
I'm sure its a badly formatted json, i just can't see where. In any case, we should catch this exception.

**Comment by ivyleavedtoadflax** [comment]
Actually reading the message this time - this is coming from `requests`.

**Comment by ivyleavedtoadflax** [comment]
So this was caused by a badly named entity in the JSON. "api_type" should have been "type". Let's add an informative message to indicate that this error may have been raised by a poorly formatted JSON. We may also want to do some checking that the input JSON is correct.
