### ISSUE TITLE
KeyError when running `endpoint test` on an endpoint that does not exist or is not ready

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/hugie#57]
```
$ hugie endpoint test multilabel-nlu-dev foobar
zsh: correct 'test' to 'tests' [nyae]? n
Traceback (most recent call last):

  File "/home/matthew/.local/bin/hugie", line 8, in <module>
    sys.exit(app())

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.8/site-packages/hugie/endpoint.py", line 297, in test
    url = info["status"]["url"]

KeyError: 'url'
```

This should be handled better

**Comment by nsorros** [comment]
I think this was fixed in https://github.com/MantisAI/hugie/commit/e11a77621e3741c8b3a89886b0328da533032093. It is now `info["status"].get("url")`
