### ISSUE TITLE
Update to meet latest hugie schema

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/hugie#77]
```
hugie endpoint list
Traceback (most recent call last):

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.10/site-packages/hugie/endpoint.py", line 38, in list
    response.raise_for_status()

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.endpoints.huggingface.cloud/endpoint


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/matthew/.local/bin/hugie", line 8, in <module>
    sys.exit(app())

  File "/home/matthew/.local/pipx/venvs/hugie/lib/python3.10/site-packages/hugie/endpoint.py", line 41, in list
    handle_requests_error(e)

TypeError: handle_requests_error() missing 1 required positional argument: 'data'
```

**Comment by ivyleavedtoadflax** [comment]
Will be resolved in #78
